In [2]:
import os
import pandas as pd

In [3]:
path = os.getcwd().replace("\\", "/")
data = pd.read_csv(path + "/toy_dataset.csv")
del data['Number']

In [38]:
list_of_city = []
for city in data['City']:
    if city not in list_of_city:
        list_of_city.append(city)

In [4]:
city = pd.get_dummies(data['City'])
gender = pd.get_dummies(data['Gender'])
data = data.merge(city, left_index=True, right_index=True)
data = data.merge(gender, right_index = True, left_index = True)
data

,City,Gender,Age,Income,Illness,Austin,Boston,Dallas,Los Angeles,Mountain View,New York City,San Diego,Washington D.C.,Female,Male
0,Dallas,Male,41,40367.0,No,0,0,1,0,0,0,0,0,0,1
1,Dallas,Male,54,45084.0,No,0,0,1,0,0,0,0,0,0,1
2,Dallas,Male,42,52483.0,No,0,0,1,0,0,0,0,0,0,1
3,Dallas,Male,40,40941.0,No,0,0,1,0,0,0,0,0,0,1
4,Dallas,Male,46,50289.0,No,0,0,1,0,0,0,0,0,0,1
5,Dallas,Female,36,50786.0,No,0,0,1,0,0,0,0,0,1,0
6,Dallas,Female,32,33155.0,No,0,0,1,0,0,0,0,0,1,0
7,Dallas,Male,39,30914.0,No,0,0,1,0,0,0,0,0,0,1
8,Dallas,Male,51,68667.0,No,0,0,1,0,0,0,0,0,0,1
9,Dallas,Female,30,50082.0,No,0,0,1,0,0,0,0,0,1,0
10,Dallas,Female,48,41524.0,Yes,0,0,1,0,0,0,0,0,1,0
11,Dallas,Male,47,54777.0,No,0,0,1,0,0,0,0,0,0,1
12,Dallas,Male,46,62749.0,No,0,0,1,0,0,0,0,0,0,1
13,Dallas,Female,42,50894.0,No,0,0,1,0,0,0,0,0,1,0
14,Dallas,Female,61,38429.0,No,0,0,1,0,0,0,0,0,1,0
15,Dallas,Male,43,34074.0,No,0,0,1,0,0,0,0,0,0,1
16,Dallas,Male,27,50398.0,No,0,0,1,0,0,0,0,0,0,1
17,Dallas,Male,38,46373.0,Yes,0,0,1,0,0,0,0,0,0,1
18,Dallas,Male,47,51137.0,No,0,0,1,0,0,0,0,0,0,1
19,Dallas,Female,35,23688.0,No,0,0,1,0,0,0,0,0,1,0
20,Dallas,Male,57,17378.0,No,0,0,1,0,0,0,0,0,0,1
21,Dallas,Male,33,45919.0,No,0,0,1,0,0,0,0,0,0,1
22,Dallas,Female,33,23001.0,No,0,0,1,0,0,0,0,0,1,0
23,Dallas,Female,27,34292.0,Yes,0,0,1,0,0,0,0,0,1,0
24,Dallas,Male,58,55190.0,No,0,0,1,0,0,0,0,0,0,1
25,Dallas,Male,64,26169.0,No,0,0,1,0,0,0,0,0,0,1
26,Dallas,Male,58,57322.0,No,0,0,1,0,0,0,0,0,0,1
27,Dallas,Male,44,61704.0,No,0,0,1,0,0,0,0,0,0,1
28,Dallas,Male,34,53619.0,No,0,0,1,0,0,0,0,0,0,1
29,Dallas,Male,45,47421.0,Yes,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149970,Austin,Female,63,99950.0,No,1,0,0,0,0,0,0,0,1,0
149971,Austin,Female,30,76928.0,No,1,0,0,0,0,0,0,0,1,0
149972,Austin,Male,46,84395.0,No,1,0,0,0,0,0,0,0,0,1
149973,Austin,Female,52,77272.0,No,1,0,0,0,0,0,0,0,1,0
149974,Austin,Female,39,90430.0,No,1,0,0,0,0,0,0,0,1,0
149975,Austin,Female,51,92132.0,No,1,0,0,0,0,0,0,0,1,0
149976,Austin,Male,49,91519.0,No,1,0,0,0,0,0,0,0,0,1
149977,Austin,Male,51,107123.0,No,1,0,0,0,0,0,0,0,0,1
149978,Austin,Male,58,100949.0,No,1,0,0,0,0,0,0,0,0,1
149979,Austin,Male,43,86737.0,No,1,0,0,0,0,0,0,0,0,1
149980,Austin,Female,53,89384.0,Yes,1,0,0,0,0,0,0,0,1,0
149981,Austin,Male,50,77134.0,No,1,0,0,0,0,0,0,0,0,1
149982,Austin,Female,47,92157.0,No,1,0,0,0,0,0,0,0,1,0
149983,Austin,Female,25,92482.0,No,1,0,0,0,0,0,0,0,1,0
149984,Austin,Male,51,99075.0,No,1,0,0,0,0,0,0,0,0,1
149985,Austin,Female,25,74947.0,No,1,0,0,0,0,0,0,0,1,0
149986,Austin,Female,63,80381.0,No,1,0,0,0,0,0,0,0,1,0
149987,Austin,Female,55,62501.0,No,1,0,0,0,0,0,0,0,1,0
149988,Austin,Female,26,77823.0,No,1,0,0,0,0,0,0,0,1,0
149989,Austin,Male,52,83688.0,No,1,0,0,0,0,0,0,0,0,1
149990,Austin,Female,26,82163.0,No,1,0,0,0,0,0,0,0,1,0
149991,Austin,Male,51,97510.0,No,1,0,0,0,0,0,0,0,0,1
149992,Austin,Male,37,88408.0,No,1,0,0,0,0,0,0,0,0,1
149993,Austin,Male,64,89906.0,No,1,0,0,0,0,0,0,0,0,1
149994,Austin,Female,37,106097.0,No,1,0,0,0,0,0,0,0,1,0
149995,Austin,Male,48,93669.0,No,1,0,0,0,0,0,0,0,0,1
149996,Austin,Male,25,96748.0,No,1,0,0,0,0,0,0,0,0,1
149997,Austin,Male,26,111885.0,No,1,0,0,0,0,0,0,0,0,1
149998,Austin,Male,25,111878.0,No,1,0,0,0,0,0,0,0,0,1
149999,Austin,Female,37,87251.0,No,1,0,0,0,0,0,0,0,1,0

In [4]:
data["target"] = data["Illness"]
del data["Illness"]
del data["City"]
del data["Gender"]
data

,Age,Income,Austin,Boston,Dallas,Los Angeles,Mountain View,New York City,San Diego,Washington D.C.,Female,Male,target
0,41,40367.0,0,0,1,0,0,0,0,0,0,1,No
1,54,45084.0,0,0,1,0,0,0,0,0,0,1,No
2,42,52483.0,0,0,1,0,0,0,0,0,0,1,No
3,40,40941.0,0,0,1,0,0,0,0,0,0,1,No
4,46,50289.0,0,0,1,0,0,0,0,0,0,1,No
5,36,50786.0,0,0,1,0,0,0,0,0,1,0,No
6,32,33155.0,0,0,1,0,0,0,0,0,1,0,No
7,39,30914.0,0,0,1,0,0,0,0,0,0,1,No
8,51,68667.0,0,0,1,0,0,0,0,0,0,1,No
9,30,50082.0,0,0,1,0,0,0,0,0,1,0,No
10,48,41524.0,0,0,1,0,0,0,0,0,1,0,Yes
11,47,54777.0,0,0,1,0,0,0,0,0,0,1,No
12,46,62749.0,0,0,1,0,0,0,0,0,0,1,No
13,42,50894.0,0,0,1,0,0,0,0,0,1,0,No
14,61,38429.0,0,0,1,0,0,0,0,0,1,0,No
15,43,34074.0,0,0,1,0,0,0,0,0,0,1,No
16,27,50398.0,0,0,1,0,0,0,0,0,0,1,No
17,38,46373.0,0,0,1,0,0,0,0,0,0,1,Yes
18,47,51137.0,0,0,1,0,0,0,0,0,0,1,No
19,35,23688.0,0,0,1,0,0,0,0,0,1,0,No
20,57,17378.0,0,0,1,0,0,0,0,0,0,1,No
21,33,45919.0,0,0,1,0,0,0,0,0,0,1,No
22,33,23001.0,0,0,1,0,0,0,0,0,1,0,No
23,27,34292.0,0,0,1,0,0,0,0,0,1,0,Yes
24,58,55190.0,0,0,1,0,0,0,0,0,0,1,No
25,64,26169.0,0,0,1,0,0,0,0,0,0,1,No
26,58,57322.0,0,0,1,0,0,0,0,0,0,1,No
27,44,61704.0,0,0,1,0,0,0,0,0,0,1,No
28,34,53619.0,0,0,1,0,0,0,0,0,0,1,No
29,45,47421.0,0,0,1,0,0,0,0,0,0,1,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
149970,63,99950.0,1,0,0,0,0,0,0,0,1,0,No
149971,30,76928.0,1,0,0,0,0,0,0,0,1,0,No
149972,46,84395.0,1,0,0,0,0,0,0,0,0,1,No
149973,52,77272.0,1,0,0,0,0,0,0,0,1,0,No
149974,39,90430.0,1,0,0,0,0,0,0,0,1,0,No
149975,51,92132.0,1,0,0,0,0,0,0,0,1,0,No
149976,49,91519.0,1,0,0,0,0,0,0,0,0,1,No
149977,51,107123.0,1,0,0,0,0,0,0,0,0,1,No
149978,58,100949.0,1,0,0,0,0,0,0,0,0,1,No
149979,43,86737.0,1,0,0,0,0,0,0,0,0,1,No
149980,53,89384.0,1,0,0,0,0,0,0,0,1,0,Yes
149981,50,77134.0,1,0,0,0,0,0,0,0,0,1,No
149982,47,92157.0,1,0,0,0,0,0,0,0,1,0,No
149983,25,92482.0,1,0,0,0,0,0,0,0,1,0,No
149984,51,99075.0,1,0,0,0,0,0,0,0,0,1,No
149985,25,74947.0,1,0,0,0,0,0,0,0,1,0,No
149986,63,80381.0,1,0,0,0,0,0,0,0,1,0,No
149987,55,62501.0,1,0,0,0,0,0,0,0,1,0,No
149988,26,77823.0,1,0,0,0,0,0,0,0,1,0,No
149989,52,83688.0,1,0,0,0,0,0,0,0,0,1,No
149990,26,82163.0,1,0,0,0,0,0,0,0,1,0,No
149991,51,97510.0,1,0,0,0,0,0,0,0,0,1,No
149992,37,88408.0,1,0,0,0,0,0,0,0,0,1,No
149993,64,89906.0,1,0,0,0,0,0,0,0,0,1,No
149994,37,106097.0,1,0,0,0,0,0,0,0,1,0,No
149995,48,93669.0,1,0,0,0,0,0,0,0,0,1,No
149996,25,96748.0,1,0,0,0,0,0,0,0,0,1,No
149997,26,111885.0,1,0,0,0,0,0,0,0,0,1,No
149998,25,111878.0,1,0,0,0,0,0,0,0,0,1,No
149999,37,87251.0,1,0,0,0,0,0,0,0,1,0,No

In [62]:
from sklearn.preprocessing import StandardScaler
std_scl = StandardScaler()
data['Age'] = std_scl.fit_transform(data['Age'])
data['Income'] = std_scl.fit_transform(data['Income'])

In [73]:
features = data.iloc[:,0:-1]
target = data.iloc[:,-1]

In [79]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2)

In [84]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

In [85]:
knn = KNeighborsClassifier(3)
dtree = DecisionTreeClassifier()
svm = SVC(kernel="rbf")
nn = MLPClassifier(hidden_layer_sizes=(5), activation='relu', solver='adam')

In [86]:
knn.fit(x_train, y_train)
dtree.fit(x_train, y_train)
svm.fit(x_train, y_train)
nn.fit(x_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=5, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [87]:
from sklearn.metrics import confusion_matrix, classification_report

In [88]:
knn_pred = knn.predict(x_test)
dtree_pred = dtree.predict(x_test)
svm_pred = svm.predict(x_test)
nn_pred = nn.predict(x_test)

In [89]:
print(confusion_matrix(y_test, knn_pred))
print(confusion_matrix(y_test, dtree_pred))
print(confusion_matrix(y_test, svm_pred))
print(confusion_matrix(y_test, nn_pred))
print(classification_report(y_test, knn_pred))
print(classification_report(y_test, dtree_pred))
print(classification_report(y_test, svm_pred))
print(classification_report(y_test, nn_pred))

[[26996   509]
 [ 2451    44]]
[[25022  2483]
 [ 2278   217]]
[[27505     0]
 [ 2495     0]]
[[27505     0]
 [ 2495     0]]
             precision    recall  f1-score   support

         No       0.92      0.98      0.95     27505
        Yes       0.08      0.02      0.03      2495

avg / total       0.85      0.90      0.87     30000

             precision    recall  f1-score   support

         No       0.92      0.91      0.91     27505
        Yes       0.08      0.09      0.08      2495

avg / total       0.85      0.84      0.84     30000

             precision    recall  f1-score   support

         No       0.92      1.00      0.96     27505
        Yes       0.00      0.00      0.00      2495

avg / total       0.84      0.92      0.88     30000

             precision    recall  f1-score   support

         No       0.92      1.00      0.96     27505
        Yes       0.00      0.00      0.00      2495

avg / total       0.84      0.92      0.88     30000

D:\programfiles\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [97]:
data[data['target'] == "No"].shape

(137861, 13)

In [95]:
data[data['target'] == "Yes"].shape

(12139, 13)

In [102]:
y_test[y_test == "No"].shape

(27505,)